[aliases]
Emacs = "emacs"
st-256color = "st"
TelegramDesktop = "telegram"
beekeeper-studio = "beekeeper"
"Org\\.gnome\\.Nautilus" = "nautilus"
Skype = "skype"

[general]
separator = ":"
wm_property = "class"

[options]
remove_duplicates = false
no_names = false
no_icon_names = false
