---
ansible_host: transmission.com
ansible_user: ansible_manager
ansible_sudo_pass: red

transmission_directory: /mnt/storage/torrents

transmission_users:
  alice:
    name: alice
    password: red
    blocklist_enabled: false
    blocklist_url: http://www.example.com/blocklist
    transmission_password: green
    transmission_port: 9091
    transmission_url: '/alice/'
    speed_limit_up: 10000
    speed_limit_down: 10000
    peer_port: 51414
  bob:
    name: bob
    password: red
    blocklist_enabled: false
    blocklist_url: http://www.example.com/blocklist
    transmission_password: green
    transmission_port: 9092
    transmission_url: '/bob/'
    speed_limit_up: 10000
    speed_limit_down: 10000
    peer_port: 51415

transmission_mount_devices:
  first_device:
    path: /mnt/storage/
    uuid: aaaaaa-bbb-10010101-01010101-010101010
    fstype: ext4
    state: mounted
