---
- name: Mount up device by UUID
  mount:
    path: "{{ item.path }}"
    src: UUID="{{ item.uuid }}"
    fstype: "{{ item.fstype }}"
    state: "{{ item.state }}"
  loop: "{{ nas_mount_devices }}"

- name: Ensure service user exists
  user:
    name: "{{ nas_user }}"
    comment: qBittorrent nox user
    shell: /usr/sbin/nologin
    system: yes
    state: present
  register: nas_user_info

- name: Ensure torrent directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ nas_user_info.name }}"
    group: "{{ nas_user_info.group }}"
  loop:
    "{{ nas_torrent_directories }}"
