---
- name: Copy example host_vars
  hosts:
    - localhost
  tasks:
    - name: Save all host_vars/*.example.yaml files to example_files variable
      find:
        paths: "{{ inventory_dir }}/host_vars"
        patterns: "*.example.yaml"
        recurse: no
      register: example_files

    - name: Copy all example_files witout example in file name to same dir
      vars:
        filename: "{{ item.path | basename | split('.') | reject('search', 'example') | join('.') }}"
      copy:
        src: "{{ item.path }}"
        dest:
          "{{ item.path | dirname }}/{{ filename }}"
        force: "{{ force_copy | default('no') }}"
      loop: "{{ example_files.files }}"
