---
- name: Copy i3wm config files
  hosts:
    - localhost
  become: yes
  no_log: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  tasks:
    - name: Ensure feh package is installed
      package:
        name: feh
        state: present
        
    - name: Copy i3wm to .config directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/"
      loop:
        - "{{ playbook_dir }}/files/i3/i3"
        - "{{ playbook_dir }}/files/i3/i3status"

    - name: Changing perm of script files, adding "+x"
      file:
        path: "{{ ansible_env.HOME }}/.config/i3/scripts"
        mode: a+x
        recurse: true
