---
- name: Configure samba on localhost
  hosts:
    - localhost
  no_log: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  tasks:
    - name: Copy credentials
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.credentials/smb"
        content: |
          user={{ hostvars.nas.nas_user }}
          password={{ hostvars.nas.nas_samba_user_password }}
          domain={{ hostvars.nas.ansible_host }}

    - name: Add samba host to fstab file
      become: yes
      blockinfile:
        path: /etc/fstab
        state: present
        block: |
          //{{ hostvars.nas.ansible_host }}/{{  hostvars.nas.nas_samba_shares_name }}    /media/{{  hostvars.nas.nas_samba_shares_name }}       cifs    uid=0,credentials=/home/dr/.credentials/smb,iocharset=utf8,vers=3.0,noperm 0 0

    - name: Apply changes
      become: yes
      ansible.builtin.shell: mount -a
