---
- name: Copy custom dmenu scripts with history support
  hosts:
    - localhost
  tasks:
    - name: Copy dmenu scripts to /usr/local/bin  directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~/.local/bin/"
        mode: a+x
      loop:
        - "{{ playbook_dir }}/files/dmenu/"

