---
- name: Copy i3wm config files
  hosts:
    - localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  tasks:
    - name: Ensure feh, i3, xset packages are installed
      package:
        name:
          - feh
          - i3
          - xset
        state: present
      become: yes
      tags: laptop, desktop

    - name: Ensure i3 directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ ansible_env.HOME }}/.config/i3"
        - "{{ ansible_env.HOME }}/.config/i3status"
      tags: laptop, desktop 
     
    - name: Copy i3wm config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/i3/i3"
        dest: "{{ ansible_env.HOME }}/.config/"
      tags: laptop, desktop

    - name: Copy i3bar for laptop config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/i3/i3status/config-laptop"
        dest: "{{ ansible_env.HOME }}/.config/i3status/config"
      tags: laptop
      
    - name: Copy i3bar for desktop config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/i3/i3status/config-desktop"
        dest: "{{ ansible_env.HOME }}/.config/i3status/config"
      tags: desktop

    - name: Changing perm of script files, adding "+x"
      file:
        path: "{{ ansible_env.HOME }}/.config/i3/scripts"
        mode: a+x
        recurse: true
      tags: laptop, desktop
