---
- name: Copy custom dmenu scripts with history support
  hosts:
    - localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  become: yes
  tasks:
    - name: Copy dmenu scripts to /usr/local/bin  directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/"
        mode: a+x
      loop:
        - "{{ playbook_dir }}/files/dmenu/"

