---
- name: Configure qbittorrent on nas
  hosts:
    - nas
  become: yes
  no_log: true
  pre_tasks:
    - name: Ensure nas is configurated
      include_tasks: configure-nas.yaml
  tasks:
    - name: Ensure package is installed
      package:
        name: qbittorrent-nox
        state: present

    - name: Return information about installed packages as facts.
      ansible.builtin.package_facts:
        manager: auto

    - name: Ensure systemd unit file is present
      template:
        src: qbittorrent/qbittorrent-nox.service.j2
        dest: /etc/systemd/system/qbittorrent-nox.service
        owner: root
        group: root
        mode: 0644
      notify:
        - restart qbittorrent
      when: "ansible_service_mgr == 'systemd'"

    - name: Start qbittorrent
      service:
        name: qbittorrent-nox
        state: started

    - name: Ensure service is enabled at boot
      systemd:
        name: qbittorrent-nox
        enabled: yes
        daemon_reload: yes
      when: "ansible_service_mgr == 'systemd'"

  handlers:
    - name: restart qbittorrent
      service:
        name: qbittorrent-nox
        state: restarted
