---
- name: Configure syncthing on nas
  hosts:
    - nas
  become: yes
  no_log: true
  pre_tasks:
    - name: Ensure nas is configurated
      include_tasks: configure-nas.yaml
  roles:
    - role: install-syncthing
      syncthing_user: "{{ nas_user }}"
