---
- name: Configure samba on nas
  hosts:
    - nas
  become: yes
  no_log: true
  pre_tasks:
    - name: Ensure nas is configurated
      include_tasks: configure-nas.yaml

  roles:
   - role: bertvv.samba
     samba_shares_root: "{{ nas_samba_shares_root }}"

     samba_users:
       - name: "{{ nas_user }}"
         password: "{{ nas_samba_user_password }}"

     samba_shares:
       - name: "{{ nas_samba_shares_name }}"
         valid_users: "{{ nas_user }}"
         write_list: "{{ nas_user }}"
         group: "{{ nas_user }}"
         browseable: "no"
         path: "{{ nas_samba_shares_root }}"
