---
- name: Configure qbittorrent
  hosts:
    - nas
  become: yes
  no_log: true
  tasks:
    - name: Mount up device by UUID
      mount:
        path: "{{ item.path }}"
        src: UUID="{{ item.uuid }}"
        fstype: "{{ item.fstype }}"
        state: "{{ item.state }}"
      loop: "{{ nas_mount_devices }}"

    - name: Ensure package is installed
      package:
        name: qbittorrent-nox
        state: present

    - name: Ensure service user exists
      user:
        name: "{{ nas_qbittorrent_nox_user }}"
        comment: qBittorrent nox user
        shell: /usr/sbin/nologin
        system: yes
        state: present
      register: nas_qbittorrent_nox_user_info

    - name: Ensure torrent directories exist
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ nas_qbittorrent_nox_user_info.name }}"
        group: "{{ nas_qbittorrent_nox_user_info.group }}"
      loop:
          "{{ nas_torrent_directories }}"

    - name: Return information about installed packages as facts.
      ansible.builtin.package_facts:
        manager: auto

    - name: Ensure systemd unit file is present
      template:
        src: qbittorrent/qbittorrent-nox.service.j2
        dest: /etc/systemd/system/qbittorrent-nox.service
        owner: root
        group: root
        mode: 0644
      notify:
        - restart qbittorrent
      when: "ansible_service_mgr == 'systemd'"

    - name: Start qbittorrent
      service:
        name: qbittorrent-nox
        state: started

    - name: Ensure service is enabled at boot
      systemd:
        name: qbittorrent-nox
        enabled: yes
        daemon_reload: yes
      when: "ansible_service_mgr == 'systemd'"

  handlers:
    - name: restart qbittorrent
      service:
        name: qbittorrent-nox
        state: restarted
