---
- name: Configure transmission
  hosts:
    - transmission
  become: yes
  no_log: true
  tasks:
    - name: Mount up device by UUID
      ansible.posix.mount:
        path: "{{ item.value.path }}"
        src: UUID="{{ item.value.uuid }}"
        fstype: "{{ item.value.fstype }}"
        state: "{{ item.value.state }}"
      loop: "{{ transmission_mount_devices | default({}) | dict2items }}"

    - name: Create transmission users
      ansible.builtin.user:
        name: "{{ item.value.name }}"
      loop: "{{ transmission_users | default({}) | dict2items }}"

    - name: Create transmission directory
      ansible.builtin.file:
        path: "{{ transmission_directory }}"
        state: directory
      when: transmission_directory is defined

    - name: Install transmission
      apt:
        name: transmission-daemon
        state: present

    - name: Make sure transmission is not running
      service:
        name: "transmission-daemon.{{ item.value.name }}.service"
        state: stopped
      ignore_errors: true
      loop: "{{ transmission_users | default({}) | dict2items }}"

    - name: Add downloads folder
      file:
        state: directory
        path: "{{ transmission_directory}}/{{ item.value.name }}/downloads"
        owner: "{{ item.value.name }}"
        group: "{{ item.value.name }}"
        mode: 0775
      loop: "{{ transmission_users | default({}) | dict2items }}"
      when: transmission_directory

    - name: Add watch dir
      file:
        state: directory
        path: "{{ transmission_directory}}/{{ item.value.name }}/watch"
        owner: "{{ item.value.name }}"
        group: "{{ item.value.name }}"
        mode: 0775
      loop: "{{ transmission_users | default({}) | dict2items }}"
      when: transmission_directory

    - name: Add incomplete folder
      file:
        state: directory
        path: "{{ transmission_directory}}/{{ item.value.name }}/incomplete"
        owner: "{{ item.value.name }}"
        group: "{{ item.value.name }}"
        mode: 0775
      loop: "{{ transmission_users | default({}) | dict2items }}"
      when: transmission_directory

    - name: Copy Transmission configuration
      template:
        src: transmission/settings.json.j2
        dest: "/home/{{ item.value.name }}/.config/transmission-daemon/settings.json"
        owner: "{{ item.value.name }}"
        group: "{{ item.value.name }}"
      loop: "{{ transmission_users | default({}) | dict2items }}"

    - name: Copy systemd unit files
      template:
        src: transmission/transmission.service.j2
        dest: "/etc/systemd/system/transmission-daemon.{{ item.value.name }}.service"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      loop: "{{ transmission_users | default({}) | dict2items }}"
      
    - name: Start transmission
      service:
        name: "transmission-daemon.{{ item.value.name }}.service"
        state: started
      ignore_errors: true
      loop: "{{ transmission_users | default({}) | dict2items }}"
